version: "3.8"
services: 
  nginx:
    image: nginx:1.21.1-alpine  
    container_name: nginx-ln
    ports: 
      - "9000:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/  
      - ./source/:/usr/share/nginx/html  